### ISSUE TITLE
Test hour module

### ISSUE THREAD

**Issue by Jumaruba** [NIAEFEUP/subject-trade#25]
Implement unit tests using python unittest.

**Comment by FilipePintoReis** [comment]
@Jumaruba Can you implement the == operator test?

**Comment by Jumaruba** [comment]
Yes, but the days of the weekend have already been implemented?

**Comment by FilipePintoReis** [comment]
@Jumaruba Yes. I was talking about that operator for hour though. It's fixed already, don't worry about it. Also, mention me when you want me to get a notification!

**Comment by EduRibeiro00** [comment]
A test method for the addition method of the Hour class is missing.
